[project]
name = "API"
version = "0.1.0"
description = "Python API base"
readme = "README.md"
requires-python = ">=3.9.6"
authors = [{ name = "Ivar Jönsson", email = "ivajns-9@student.ltu.se" }]

[project.urls]
"source" = "https://github.com/ivario123/NGAC_ABE"
