on: [pull_request]
name: Unit Tests

jobs:
  # Builds the NGAC servers for LINUX, WINDOWS, and MACOS
  # And commits and pushes them to the repo branch "ngac_exec_{os}"
  build_linux:
    name: Build NGAC for Linux
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install SWI Prolog
        run: sudo apt-get install swi-prolog
      - name: Build NGAC
        run: |
          echo "Cloning the TOG-NGAC repo"
          git clone https://github.com/tog-rtd/tog-ngac-crosscpp
          echo "Building the NGAC server"
          cd tog-ngac-crosscpp
          swipl -v -o ngac -g ngac -c ngac.pl
          swipl -v -o ngac_server -g ngac_server -c ngac-server.pl

          echo "Building the CME server"
          swipl -v -o cme_sim -g cme_server -c cme_server.pl

          echo "Building the PEP server"
          cd PEP-RAP
          swipl -v -o pep_server -g pep_server -c pep.pl

          echo "SUCCESS: NGAC server built"
      - name: Commit and push NGAC server
        run: |
          echo "Committing and pushing the NGAC server"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          git checkout -b ngac_exec_linux
          git add tog-ngac-crosscpp/ngac tog-ngac-crosscpp/ngac_server tog-ngac-crosscpp/cme_sim tog-ngac-crosscpp/PEP-RAP/pep_server
          git commit -m "NGAC server built for Linux"
          git push --set-upstream origin ngac_exec_linux
  build_windows:
    name: Build NGAC for Windows
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install SWI Prolog
        run: choco install swi-prolog
      - name: Build NGAC
        run: |
          echo "Cloning the TOG-NGAC repo"
          git clone
          echo "Building the NGAC server"
          cd tog-ngac-crosscpp
          swipl -v -o ngac -g ngac -c ngac.pl
          swipl -v -o ngac_server -g ngac_server -c ngac-server.pl

          echo "Building the CME server"
          swipl -v -o cme_sim -g cme_server -c cme_server.pl

          echo "Building the PEP server"
          cd PEP-RAP
          swipl -v -o pep_server -g pep_server -c pep.pl

          echo "SUCCESS: NGAC server built"
      - name: Commit and push NGAC server
        run: |
          echo "Committing and pushing the NGAC server"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          git checkout -b ngac_exec_windows
          git add tog-ngac-crosscpp/ngac.exe tog-ngac-crosscpp/ngac_server.exe tog-ngac-crosscpp/cme_sim.exe tog-ngac-crosscpp/PEP-RAP/pep_server.exe
          git commit -m "NGAC server built for Windows"
          git push --set-upstream origin ngac_exec_windows

  build_macos:
    name: Build NGAC for MacOS
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install SWI Prolog
        run: brew install swi-prolog
      - name: Build NGAC
        run: |
          echo "Cloning the TOG-NGAC repo"
          git clone
          echo "Building the NGAC server"
          cd tog-ngac-crosscpp
          swipl -v -o ngac -g ngac -c ngac.pl
          swipl -v -o ngac_server -g ngac_server -c ngac-server.pl

          echo "Building the CME server"
          swipl -v -o cme_sim -g cme_server -c cme_server.pl

          echo "Building the PEP server"
          cd PEP-RAP
          swipl -v -o pep_server -g pep_server -c pep.pl

          echo "SUCCESS: NGAC server built"
      - name: Commit and push NGAC server
        run: |
          echo "Committing and pushing the NGAC server"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          git checkout -b ngac_exec_macos
          git add tog-ngac-crosscpp/ngac tog-ngac-crosscpp/ngac_server tog-ngac-crosscpp/cme_sim tog-ngac-crosscpp/PEP-RAP/pep_server
          git commit -m "NGAC server built for MacOS"
          git push --set-upstream origin ngac_exec_macos
