name: Lint
on: [pull_request, push]
jobs:
  black:
    name: Python Code Format Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install black

      - name: Check for black errors
        run: black --check --diff .
        continue-on-error: true

      - name: Handle black errors
        if: ${{ failure() }} && github.event_name == 'pull_request'
        run: |
          git checkout ${{ github.head_ref }}
          echo "Black found errors. Formatting code..."
          black .
          echo "Checking for black errors again..."
          black --check --diff .
          echo "Black formatted code. Committing changes..."
          git config --local user.email "{{ github.actor }}@users.noreply.github.com"
          git config --local user.name "{{ github.actor }}"
          git add .
          git commit -m "Format Python code with black"
          git push
      - name: Fail if there are any errors
        if: ${{ failure() }} && github.event_name != 'pull_request'
        run: exit 1
