on: [push]
name:
  Unit Tests

  # - name: Build NGAC
  #   run: |
  #     git pull
  #     echo "Cloning the TOG-NGAC repo"
  #     git clone https://github.com/tog-rtd/tog-ngac-crosscpp
  #     echo "Building the NGAC server"
  #     cd tog-ngac-crosscpp
  #     swipl -v -o ngac -g ngac -c ngac.pl
  #     swipl -v -o ngac_server -g ngac_server -c ngac.pl
  #     echo "Building the CME server"
  #     swipl -v -o cme -g cme -c cme_sim.pl
  #     echo "Building the PEP server"
  #     cd PEP-RAP
  #     swipl -v -o pep_server -g pep_server -c pep.pl
  #     echo "SUCCESS: NGAC server built"
  #     echo "Coppying the NGAC server, into src/NGAC/executables/linux"
  #     mkdir -p ../../src/NGAC/executables/linux
  #     cp ../ngac ../ngac_server ../cme ./pep_server ../../src/NGAC/executables/linux
  #     cd ../../src/NGAC/executables
jobs:
  test_servers_by_calling_them_from_bash:
    name: Test servers by calling them from bash
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run the servers
        run: |
          echo "Install SWI Prolog"
          sudo apt-get install swi-prolog
          echo $PATH
          ls /usr/bin
          ls /usr/lib/swi-prolog
          ls /usr/lib/swi-prolog/bin
          ls /usr/lib/swi-prolog/bin/amd64
          cd src/NGAC/executables/
          echo "Starting the servers individually"
          cd linux
          sleep 20
          ./ngac_server &
          ./cme &
          ./pep_server &
          cd ..
          sleep 5
          echo "Killing the servers"
          killall swipl
          echo "SUCCESS: Servers killed"
          echo "Starting the servers in a group"
          
          bash start_ngac.sh
          sleep 5
          killall swipl
          sleep 2
  test_linux:
    needs: test_servers_by_calling_them_from_bash
    name: Test on Linux
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install SWI Prolog
        run: sudo apt-get install swi-prolog
      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests
          pip install pytest
          pip install pytest-cov

      - name: Run tests
        run: |
          cd src/NGAC
          pytest test_ngac.py --cov=ngac --cov-report=xml --cov-report=html

# jobs:
#   test_linux:
#     name: Test on Linux
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v2
#       - name: Install SWI Prolog
#         run: sudo apt-get install swi-prolog
#       - name: Set up Python 3.8
#         uses: actions/setup-python@v1
#         with:
#           python-version: 3.8
#       - name: Install dependencies
#         run: |
#           python -m pip install --upgrade pip
#           pip install pytest
#           pip install requests
#       - name: Run tests
#         run: |
#           cd ./src
#           pytest ./test.py -o log_cli=true -o log_cli_level=INFO
#           cd ./NGAC
#           pytest ./test_executables.py -o log_cli=true -o log_cli_level=INFO
#           cd ./executables
#           python3 .

#   test_macos:
#     name: Test on MacOS
#     runs-on: macos-latest
#     steps:
#       - uses: actions/checkout@v2
#       - name: Install SWI Prolog
#         run: brew install swi-prolog
#       - name: Set up Python 3.8
#         uses: actions/setup-python@v1
#         with:
#           python-version: 3.8
#       - name: Install dependencies
#         run: |
#           python -m pip install --upgrade pip
#           pip install pytest
#           pip install requests
#       - name: Run tests
#         run: |
#           cd ./src
#           pytest ./test.py -o log_cli=true -o log_cli_level=INFO
#           cd ./NGAC
#           pytest ./test_executables.py -o log_cli=true -o log_cli_level=INFO
#           cd ./executables
#           python3 .

#   test_executables_standalone_mac:
#     name: Test executables standalone on MacOS
#     runs-on: macos-latest
#     steps:
#       - uses: actions/checkout@v2
#       - name: Install SWI Prolog
#         run: brew install swi-prolog
#       - name: Set up Python 3.8
#         uses: actions/setup-python@v1
#         with:
#           python-version: 3.8
#       - name: Install dependencies
#         run: |
#           python -m pip install --upgrade pip
#           pip install pytest
#           pip install requests
#       - name: Run tests
#         run: |
#           cd ./src
#           cd ./NGAC
#           cd ./executables
#           python3 .
