on: [push]
name: Unit Tests

jobs:
  test_linux:
    name: Test on Linux
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install SWI Prolog
        run: sudo apt-get install swi-prolog
      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest
          pip install requests
      - name: Run tests
        run: |
          cd ./src
          pytest ./test.py -o log_cli=true -o log_cli_level=INFO
          cd ./NGAC
          pytest ./test_executables.py -o log_cli=true -o log_cli_level=INFO
          cd ./executables
          python .

  test_macos:
    name: Test on MacOS
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install SWI Prolog
        run: brew install swi-prolog
      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest
          pip install requests
      - name: Run tests
        run: |
          cd ./src
          pytest ./test.py -o log_cli=true -o log_cli_level=INFO
          cd ./NGAC
          pytest ./test_executables.py -o log_cli=true -o log_cli_level=INFO
          cd ./executables
          python .

  test_executables_standalone_mac:
    name: Test executables standalone on MacOS
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install SWI Prolog
        run: brew install swi-prolog
      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest
          pip install requests
      - name: Run tests
        run: |
          cd ./src
          cd ./NGAC
          cd ./executables
          python .
