on: [push]
name: Unit Tests

jobs:
  test_ngac_simple:
    name: Simple NGAC Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests
          pip install pytest
          pip install pytest-cov

      - name: Run tests
        run: |
          cd src/NGAC/exutables
          python ngac_server.py
  test_linux:
    needs: test_ngac_simple
    name: Test on Linux
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests
          pip install pytest
          pip install pytest-cov

      - name: Run tests
        run: |
          cd src/NGAC
          pytest test_ngac.py --cov=ngac --cov-report=xml --cov-report=html

# jobs:
#   test_linux:
#     name: Test on Linux
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v2
#       - name: Install SWI Prolog
#         run: sudo apt-get install swi-prolog
#       - name: Set up Python 3.8
#         uses: actions/setup-python@v1
#         with:
#           python-version: 3.8
#       - name: Install dependencies
#         run: |
#           python -m pip install --upgrade pip
#           pip install pytest
#           pip install requests
#       - name: Run tests
#         run: |
#           cd ./src
#           pytest ./test.py -o log_cli=true -o log_cli_level=INFO
#           cd ./NGAC
#           pytest ./test_executables.py -o log_cli=true -o log_cli_level=INFO
#           cd ./executables
#           python3 .

#   test_macos:
#     name: Test on MacOS
#     runs-on: macos-latest
#     steps:
#       - uses: actions/checkout@v2
#       - name: Install SWI Prolog
#         run: brew install swi-prolog
#       - name: Set up Python 3.8
#         uses: actions/setup-python@v1
#         with:
#           python-version: 3.8
#       - name: Install dependencies
#         run: |
#           python -m pip install --upgrade pip
#           pip install pytest
#           pip install requests
#       - name: Run tests
#         run: |
#           cd ./src
#           pytest ./test.py -o log_cli=true -o log_cli_level=INFO
#           cd ./NGAC
#           pytest ./test_executables.py -o log_cli=true -o log_cli_level=INFO
#           cd ./executables
#           python3 .

#   test_executables_standalone_mac:
#     name: Test executables standalone on MacOS
#     runs-on: macos-latest
#     steps:
#       - uses: actions/checkout@v2
#       - name: Install SWI Prolog
#         run: brew install swi-prolog
#       - name: Set up Python 3.8
#         uses: actions/setup-python@v1
#         with:
#           python-version: 3.8
#       - name: Install dependencies
#         run: |
#           python -m pip install --upgrade pip
#           pip install pytest
#           pip install requests
#       - name: Run tests
#         run: |
#           cd ./src
#           cd ./NGAC
#           cd ./executables
#           python3 .
